// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const databaseUrl = process.env["DATABASE_URL"];
if (!databaseUrl) {
  throw new Error("DATABASE_URL is not set");
}

if (!databaseUrl.startsWith("postgresql://") && !databaseUrl.startsWith("postgres://")) {
  throw new Error(
    `DATABASE_URL must be a postgres connection string (postgresql://...). Got: ${databaseUrl.split("://")[0]}://...`,
  );
}

try {
  const parsed = new URL(databaseUrl);
  if (
    parsed.hostname === "localhost" &&
    (parsed.port === "51213" || parsed.port === "51214")
  ) {
    throw new Error(
      "DATABASE_URL is pointing at Prisma local dev database (localhost:51213/51214). Set it to your real Postgres (e.g. Supabase) URL.",
    );
  }
} catch {
  throw new Error("DATABASE_URL is not a valid URL");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
